### ISSUE TITLE
replace x25519 with x448

### ISSUE THREAD

**Issue by david415** [katzenpost/doubleratchet#11]
If memguard dev team solves for https://github.com/awnumar/memguard/issues/140 then we should replace x25519 with x448, in particular I was thinking to use this implementation of x448: https://pkg.go.dev/github.com/cloudflare/circl@v1.0.0/dh/x448

**Comment by Yawning** [comment]
There are very few realistic scenarios where, X25519 is not ok, and X448 is.  This will do rather nasty things to performance since group operations will be significantly more expensive.

**Comment by david415** [comment]
@Yawning I hear what you're saying and agree with you 100%. That having been said, it seems noteworthy to point out that we are already using X25519 in our Noise wire protocol and in our Sphinx packet format. If there was some huge unforeseen attack on X25519 then it would be nice if not every protocol layer of ours was broken.

Another idea I had for solving for  "a break in X25519 breaks all our protocols" would be to make a naive hybrid ratchet construction with SIDH or CSIDH. We basically do not care much about performance since it's only on the client.

That is, we can have two "DH ratchets". One that uses ECDH and the other use SIDH or CSIDH. Each public key exchange would exchange two keys instead of one so that both "DH" ratchets would step forward at the same time and both feed their shared secrets into the root KDF chain etc. Naive because it's simple and performance would be terrible but it should work okay.

If we just resign ourselves to have shit performance on the double ratchet, then would you rather I do this PQ hybrid approach than use X448? Do you have any other recommendations?
